### ISSUE TITLE
`maxUnavailable: 0` can cause problems when `replica: 1`

### ISSUE THREAD

**Issue by colearendt** [rstudio/helm#170]
Because the deployment (if unhealthy) never gets into a very happy state / cannot roll over

**Comment by bschwedler** [comment]
I ran into a similar issue with licenses leaking during a rolling upgrade when testing this.

We are already setting `MaxSurge` to `100%` so I don't know the best approach here. If both `ReplicaSets` are unhappy in the rollout, it's likely going to require some manual intervention.
