### ISSUE TITLE
invalid yaml spec required for duplicate keys

### ISSUE THREAD

**Issue by scott-grimes** [rstudio/helm#180]
In order to configure LDAP for rstudio-connect the following entry is required in the values file to allow multiple groups to login:

```
config:
  'LDAP "My Config"]:
    PermittedLoginGroup: cn=some-group
    PermittedLoginGroup: cn=other-group
```

this violates yaml spec (https://yaml.org/spec/1.2.2/) which requires keys be unique, and causes all kinds of problems when attempting to deploy via helm, kustomize, or any other tool. Right now it's not possible for us to deploy this and allow more than one group to login

similar problems exist for many other config values like `Authorization.AdministratorRoleMapping` which are supposed to be defined multiple times.

One fix for this would be to configure the configmap template helper function in helm to generate entries based on either strings, for single entries, or an array of strings, for multiple entries. The canonical solution for this is to check the `typeOf` the value and iterate accordingly:

```
# values.yaml
config:
  'LDAP "My Config"':
    PermittedLoginGroup: 
    - cn=some-group
    - cn=other-group
```

When rendering key/values, we check if the value is a string and render directly, otherwise iterate and write your duplicate keys into the configmap:

```
# generation snippet
...
{{- range $key, $val := .items }}
{{- if kindIs "string" $val }}
  {{ $key }}: {{ $val }}
{{ else }}
{{ range $val }}
  {{ $key }}: {{ . }}
    {{- end }}
{{- end }}
```

**Comment by bschwedler** [comment]
Hi @scott-grimes  Thanks for submitting this issue!

We had a similar issue with the `rstudio-workbench` chart and came up with a [similar workaround](https://github.com/rstudio/helm/pull/176/files#diff-6a83dfcd0a1af4d2eaeb5838295f29c602a274dcb33de1b8eec5900632e4f1a6R53-R62).

Using the library chart in the PR, this is the following output for your proposed values. Can you confirm whether this renders properly for your use case?

```yaml
---
# Source: rstudio-connect/templates/configmap.yaml
(... snip ...)
data:
  rstudio-connect.gcfg: |
    [LDAP "My Config"]
    PermittedLoginGroup = cn=some-group
    PermittedLoginGroup = cn=other-group
    (... snip ...)
```

**Comment by scott-grimes** [comment]
beautiful, that works great

```
# delme-values.yaml
config:
  'LDAP "My Config"':
    PermittedLoginGroup: 
    - cn=some-group
    - cn=other-group
```

`helm template . --values delme-values.yaml -s templates/configmap.yaml`

yields 
```
---
# Source: rstudio-connect/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-rstudio-connect-config
  namespace: prod
data:
  rstudio-connect.gcfg: |
    [Authentication]
    Provider = password
    
    [HTTP]
    Listen = :3939
    
    [LDAP "My Config"]
    PermittedLoginGroup = cn=some-group
    PermittedLoginGroup = cn=other-group
...
```

**Comment by bschwedler** [comment]
Hi @scott-grimes

These changes have made it into all of the charts. For connect this is version `0.2.32`.

I am closing this issue, but please re-open it if you run into problems using this.
