### ISSUE TITLE
Enable SIGINTs by default in Connect helm chart

### ISSUE THREAD

**Issue by dbkegley** [rstudio/helm#182]
We should enable the following Connect settings in our helm chart:

```
[Scheduler]
TerminationTimeout = 3s
[Applications]
RuntimeSessionGrace = 2s
```

This fixes interactive content pods going to the `Error` state after they are terminated by Connect.

cc @christierney do you have any recommendations for what defaults we should use here?

This depends on Connect `2022.04.0`

**Comment by christierney** [comment]
I think 3s and 2s is fine; in practice I think folks will rarely if ever hit that. Once we publicize this more, if anyone starts to do actual shutdown stuff in their code then it will be very context-dependent how much time they need.

**Comment by dbkegley** [comment]
We plan to enable this by default on the Connect side in the next release so I'm going to close this since it's OBE
