### ISSUE TITLE
rstudio-pm pod metadata labels

### ISSUE THREAD

**Issue by teetiaine** [rstudio/helm#206]
Could you add a way to add metadata label to the pod template using the rstudio-pm helm chart values.yaml, similar to workbench and connect charts?

apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    aadpodidbinding: <aad_pod_identity_name>

https://github.com/rstudio/helm/blob/03b3cb610ee38a0dbdd1236cfad32dd6760ce13d/charts/rstudio-pm/values.yaml#L92

**Comment by colearendt** [comment]
Most definitely! Apologies for missing the consistency there!
