### ISSUE TITLE
rbac: pods/log actions

### ISSUE THREAD

**Issue by wmcdona89** [rstudio/helm#215]
My k8s environment does not currently allow  `Verbs:["create" "update" "patch" "delete"]` for `Resources:["pods/log"]`

Any insight as to why these permissions are needed?

Could "pods/log" be limited to ["get" "watch" "list"]?

e.g.
`Resources:["pods/log"]` -> `Verbs:["get" "watch" "list"]`
`Resources:["pods", "pods/attach", "pods/exec"]` -> `Verbs:["get" "watch" "list" "create" "update" "patch" "delete"]`

**Comment by atheriel** [comment]
I'm not sure of the exact reason, but it might be worth a try to modifying the RBAC yourself and testing whether the product still works.

**Comment by colearendt** [comment]
Ahh interesting! Thanks for reporting. I think this is probably just a holdover from us shoving `pods/logs` in with the other `pods` resources here:

https://github.com/rstudio/helm/blob/cf51385a88a913af34db39cef0422f417724da63/charts/rstudio-library/templates/_rbac.tpl#L79-L83

I don't expect that we would have any issues restricting this!
