### ISSUE TITLE
RSC: include file name in error messages?

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#260]
I am currently stuck in a specific RSC deployment on azure and having a hard time figuring out what file/mount actually causes the problem. I am facing the following error message and was wondering whether it could include the file name within the message for simplified debugging?

I am suspecting its the `/etc/rstudio-connect/launcher/rstudio-connect-launcher.key` file here but I am not entirely sure.

```
connect time="2022-08-04T07:51:37.913Z" level=fatal msg="Error: Unable to apply the configuration: Encryption key file mode must be 0600."
```

**Comment by pat-s** [comment]
I found that it was caused by `/var/lib/rstudio-connect/db/secret.key` being 777 instead of 600 because we've been using a dynamically provisioned PV which enforced 777.

**Comment by aronatkins** [comment]
I'll take this as Connect issue [21904](https://github.com/rstudio/connect/issues/21904) and get the filename included in these errors.
