### ISSUE TITLE
`sessionSecret` not mounted into session pods?

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#270]
I am using `config.sessionSecret` to mount `odbc.ini` into both server and session pod.
This was working at some point but I've recently realized that `odbc.ini` is not longer mounted into the session pod.

I only see the following mounts for session pods (NB: shared-storage lives within /home)

```yaml
Mounts:                                                                                                                                                          
  /home from mount0 (rw)                                                                                                                                         
  /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6q5qp (ro)
```

I see `sessionSecret` being mounted correctly into the server pod. Contents of the secret are also fine.

```yml
Mounts
  [...]
  /mnt/session-secret/ from rstudio-session-secret (rw)
```

I went back until chart version v0.5.12 but was not successful in restoring the mount.
I also could not infer from the chart which mounts are used for the session pods.

Has something changed or is this a configuration issue on my side?

**Comment by pat-s** [comment]
`/mnt/configmap/rstudio/launcher-mounts` NB: I've never set `config. serverDcf.launcher-mounts` before)

```
ClaimName: pvc-rsw-home-efs
MountPath: /home
MountType: KubernetesPersistentVolumeClaim
```

I am missing the following mount in my sessions (which is present when using the vanilla chart and default images). I am trying to figure out why it's missing - something apparently prevents this mount for session pods at my setup 

```
/mnt/session-configmap/rstudio from session-config (rw) 
```

Responsible lines for the mount are

- https://github.com/rstudio/helm/blob/main/charts/rstudio-workbench/templates/_helpers.tpl#L104-L106
- https://github.com/rstudio/helm/blob/main/charts/rstudio-workbench/templates/_helpers.tpl#L234-L237

AHHH found it!

I had set

```yml
config:
  server:
    launcher.kubernetes.conf:
      use-templating: 1
```

from https://docs.rstudio.com/ide/server-pro/latest/job_launcher/kubernetes_plugin.html#kube-config.

Removing that session brings back the additional mount points in the session image! It seems to override the `job-json-overrides` definitions of the chart and by that suppressing/deleting the session mount points.

**Comment by colearendt** [comment]
Just a follow-up on this one. Instead of `use-templating: 1`, you can now use `launcher.useTemplates=true`. Then we will set `use-templating` and other config (i.e. like enabling the sessions, etc.) for you. 😄 

I just checked to ensure that the `sessionSecret` should be mounted now when using that setup!
