### ISSUE TITLE
RSC: affinity for launcher pods

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#283]
Pods deployed via the launcher (using off-host execution) do not respect the `pod.affinity` definition in the helm chart. Would be great if the setting could be honored or if launcher pods could even have a distinct affinity definition.

Related to #223

**Comment by colearendt** [comment]
Thanks for the note here @pat-s ! We will take a look at why that is not being respected! Are you talking about the Workbench or Connect chart here?

When you say "have a distinct affinity definition," do you mean "per app" or "per user" or something of that nature? Something else?
