### ISSUE TITLE
PM: rootless with file-license possible?

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#321]
Attempting to upgrade from chart 0.3.x to 0.5.x including the rootless change in 0.4.0

During startup I noticed PM was unable to read the license. Inspecting further I saw that `/opt/rstudio-pm/bin/license-manager activate-file` errors with

```
Error activate-file: (44): root privilege is required to execute the activate-file command
```

Is the use of a file license a blocker for running PM rootless?

**Comment by colearendt** [comment]
Oh no! I hope not 😮 

Is it possible that you have an independent build of the container? We did make some changes to the activation process - you have to add a `--userspace` argument to make the activation work in rootless mode, I believe.

https://github.com/rstudio/rstudio-docker-products/blob/92740d7c45fc66a51f8887416875749790bcd822/package-manager/startup.sh#L20

**Comment by pat-s** [comment]
Good catch with `--userspace`! However I get the exact same error when appending it and in our (custom) startup script we even have `--userspace` already appended to the `license-manager` calls.

Seeing all the documentation about user namespacing, I suspect the following messages to be the issue:

```
You are using a supported kernel (5.10.135), but user namespaces are not supported: reason unknown.

Info: Unable to use user namespace sandboxing: "Error running the reexec.Command for [nsParent  echo]: fork/exec /proc/self/exe: operation not permitted
```

We're using Ubuntu Focal here, so I'd expect full support for user namespacing 🤔 
I had enabled `enableSandboxing:  false` so this is probably expected.

With `enableSandboxing: true` I get

```
Info: Unable to use user namespace sandboxing: "Error running the reexec.Command for [nsParent  echo]: fork/exec /proc/self/exe: no space left on device"
```

`no space left on device` is a bit strange as a `df -h` shows no disk-space related issues. Also ephemeral storage is not an issue and has a limit of up to 20 GB 🤔 

At this point I don't know what to try next. I think the root of the issue is that user namespacing does not work but I don't understand why it fails 😞

**Comment by colearendt** [comment]
Very strange!! is this on AKS again? Is there any chance that writing to the ephemeral file system has been disabled? ReadOnly or whatnot?

Also, the kernel may be pointing at the underlying host OS - is Focal your container OS? What is the OS of your Kubernetes hosts?

**Comment by pat-s** [comment]
> Very strange!! is this on AKS again?

No, this time on our EKS dev cluster. 

> Is there any chance that writing to the ephemeral file system has been disabled?

Not that I am aware of (and I am in full charge of the cluster 😄)

> Also, the kernel may be pointing at the underlying host OS - is Focal your container OS? What is the OS of your Kubernetes hosts?

The host OS is [bottlerocket](https://github.com/bottlerocket-os/bottlerocket) 1.11.1 and also comes with 5.10. Maybe bottlerocket does not support user namespacing?
Yet if I exec into the pod directly and query the kernel version via `uname -r` I get also 5.10.135 - so the reported version might be the one from the container?
How would the startup command infer the kernel version from the underlying node OS?

In the (non-healthy) pod, `cat /proc/sys/user/max_user_namespaces` also returns 0, indicating no user namespacing. Which I am a bit surprised of as we are just building based on the latest `ubuntu:focal` image and I thought [user namespacing is available by default on Ubuntu](https://docs.posit.co/rspm/admin/process-management/#ubuntu-opensusesles)?

**Comment by pat-s** [comment]
> Containers in general do not use their own kernel (it is one of the main benefits of using containers over VMs), but it would be interesting if the ubuntu container "behaved" like it was using its own kernel / reported that it was haha.

Uhh that is embarrassing 🙈 TIL...
This is really a big misconception on my side.

Anyway, WRT to kernel: 

```
uname -r
5.10.135
```

originating from bottlerocket-1.11.1

**Comment by colearendt** [comment]
Oh no worries at all!! It's one of those more advanced / nuanced container shenanigans haha. 😄 What do you get from this inside the container? (You can always start the container with `cmd=["sleep"]`, `args=["infinity"]`:

```
/opt/rstudio-pm/bin/license-manager get-verify
```

Is it possible that there is a `verify` file in your DataDir? By default at `/var/lib/rstudio-pm/verify`. If this file exists and is owned by root, it would explain these errors at least. And the remedy would be to remove it. We try to do this automatically, but sometimes that doesn't work properly 😅

**Comment by pat-s** [comment]
> Is it possible that there is a verify file in your DataDir?

Nope, checked it.

> What do you get from this inside the container?

Running this from a container without startup execution, i.e. just sleeping:

```
/opt/rstudio-pm/bin/license-manager get-verify

TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/var/log/rstudio/rstudio-server/license-manager.log'.
{"path":"","license-scope":"system","initialized":false,"result":0}
```

---

We haven't changed anything in our own build logic since the 2022.07 release which builds fine and we've been running for the past months. The main issue that I suspect currently is the apparent missing user namespace support for the underlying bottlerocket (kernel) and/or OS in general? Which seems to be an important requirement for many tasks in the new 2022.12 build when aiming to run rootless, is that correct?
Judging from the message I'd guess it comes from the OS and not the kernel.

```
You are using a supported kernel (5.10.135), but user namespaces are not supported: reason unknown.
```

AFAICS you're running on AL2 (which we have done before as well) which seems to work well.

Running `cat /proc/sys/user/max_user_namespaces` also returns 0, indicating that user namespacing is not enabled. 

Given the minimalist approach of [bottlerocket OS](https://aws.amazon.com/bottlerocket/faqs/?nc=sn&loc=2), I think it's likely that it's missing user namespace support.

Ah, I've found the confirmation that [bottlerocket disables user namespaces by default](https://github.com/bottlerocket-os/bottlerocket/issues/1982#issuecomment-1061231936).

I will try to change this setting via the "user data" approach and report back!

**Comment by pat-s** [comment]
Got it!

So it was a mix of two issues AFAICS:

- bottlerocket does not have user namespacing enabled by default. I had to supply user data and enable it via bootstrap args in the node group and define something like
  ```
  [settings.kernel.sysctl]
   "user.max_user_namespaces" = "16384"
  ```

- In the image build: I had not set `RSTUDIO_INSTALL_NO_LICENSE_INITIALIZATION=1` during the `.deb` installation in our image build. This causes the license-manager to issue a trial license via the root user at this point (as `USER rstudio-pm` is only set later). If later in the Dockerfile then, `USER rstudio-pm` is called and then `license-manager initialize`, the `--userspace` scoping won't have an effect and results in 

   ```
   {"result":44,"action":"initialize","message":"root privilege is required to execute the 
    initialize command"}
   ```

  Only when invoking the first call to `license-manager` using the `rstudio-pm` user allows a correct initialization of the userspace scope AFAICS. I didn't pay attention to this issue until now as it didn't cause the CI build to abort.


I hope this is at least partly true and somewhat helpful for others that arrive here :) Thanks for your help along the way, definitely helped me a lot to seek into the right direction! 🙏

**Comment by colearendt** [comment]
That's super helpful! Thanks for the thorough writeup and great sleuthing!! And glad to hear you have things up and running!!
