### ISSUE TITLE
Cannot connect to Oracle database: Can't open lib liboracleodbc_sb64.so file not found

### ISSUE THREAD

**Issue by smokedlinq** [rstudio/helm#324]
I checked on the session pod that the file and directory actually exist.

## Error

<img width="296" alt="image" src="https://user-images.githubusercontent.com/415528/207727220-62588927-d38b-4cd3-a2f1-0a78cb224975.png">

## POD filesystem

```text
root@session-84d28cfc78a3117e45d49-user1---rstudio-session-j8nzt:/# ll /opt/rstudio-drivers/oracle/bin/lib/liboracleodbc_sb64.so
-rw-r--r-- 1 root root 44739392 Sep 30  2021 /opt/rstudio-drivers/oracle/bin/lib/liboracleodbc_sb64.so
```

**Comment by colearendt** [comment]
Interesting!! Would you mind testing the full filepath's permissions and sharing the output here? There may be an intermediate directory causing issues:
```
namei -l /opt/rstudio-drivers/oracle/bin/lib/liboracleodbc_sb64.so
```

**Comment by smokedlinq** [comment]
```
f: /opt/rstudio-drivers/oracle/bin/lib/liboracleodbc_sb64.so
drwxr-xr-x root root /
drwxr-xr-x root root opt
drwxr-xr-x root root rstudio-drivers
drwxr-xr-x root root oracle
drwxr-xr-x root root bin
drwxr-xr-x root root lib
-rw-r--r-- root root liboracleodbc_sb64.so
```

**Comment by colearendt** [comment]
Sad days. Looks just fine 😢 There may be some other strangeness afoot - oracle in particular is a _super_ weird one. Would you mind submitting a support ticket to support@posit.co? We can get the team more used to the drivers involved. This doesn't look to me like docker is playing a part here, unless it's that we need the "oracle-client" or whatever inside of the container.

**Comment by smokedlinq** [comment]
All set, ticket #83399

**Comment by smokedlinq** [comment]
@colearendt support is saying the driver is needed. Can this be added to the image?

**Comment by smokedlinq** [comment]
@colearendt, hoping everyone is back from holiday. Is this something we can get added to the base image?

**Comment by colearendt** [comment]
Going to clone this and track at https://github.com/rstudio/rstudio-docker-products/issues/458

Helm will pick up Oracle from the containers.
