### ISSUE TITLE
Custom fonts in Workbench session

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#342]
In non-k8s installations placing custom fonts in `/etc/rstudio/fonts` works fine.

In k8s sessions however, fonts in this place are not picked up by the IDE. The installation procedure is scripted and the font files are present in the session pods under `/etc/rstudio/fonts`.

Is additional linking needed to make the custom fonts being picked up in a k8s session? Or do they need to be placed in `/mnt/rstudio/session-configmap` instead?

**Comment by colearendt** [comment]
Yeah, you probably want to put them in `session-configmap`. If they are baked into the image, you should bake them into `/mnt/dynamic/rstudio`, because `session-configmap` gets overwritten by a configmap 😄 

Check out `XDG_CONFIG_DIRS` env var to see where config gets picked up from 😄

**Comment by pat-s** [comment]
Thanks!

```
echo $XDG_CONFIG_DIRS
/mnt/dynamic:/mnt/session-configmap:/mnt/secret-configmap:/mnt/configmap:/mnt/load-balancer/
```

And yes, `/mnt/dynamic/rstudio/fonts` did the trick! 🎉
