### ISSUE TITLE
Connect: Only one `ghcr.io/rstudio/content-base:r4.1.3-py3.10.4-bionic ` has quarto installed

### ISSUE THREAD

**Issue by SamEdwardes** [rstudio/helm#347]
Only one of the default runtime yaml images has quarto configured. Is this correct? Should they all have quarto?

https://github.com/rstudio/helm/blob/c48d94fda4562795ca9010f334c2c11271a8073f/charts/rstudio-connect/default-runtime.yaml#L126-L140

**Comment by SamEdwardes** [comment]
Never mind, I see why we do this:

https://github.com/rstudio/rstudio-docker-products/blob/ff278dbeaa93503c3ab61024374e78e3cb993b49/content/base/maybe_install_quarto.sh#L1-L11

**Comment by aronatkins** [comment]
@SamEdwardes There is no requirement that all of the content-base images have any of R, Python, or Quarto. We wanted to create a "reasonable" set of starting points for folks, build some likely-to-be-used-together combinations, and then let things evolve from there.

It probably makes sense to try to always have an image with the latest R, Python, and Quarto releases, but beyond that, there aren't any must-have combinations.

We wanted to avoid huge images with all the possible R, Python, and Quarto images. We also wanted to avoid having one image for every possible combination.

If you see combinations that you think would be useful, we should add them!
