### ISSUE TITLE
Posit Connect pod scheduling

### ISSUE THREAD

**Issue by JarritB** [rstudio/helm#352]
Hi all,

I have already noticed some questions about this, but is there a particular reason the connect server itself has no options for tolerations and nodeSelector? This is available for the workbench server and the connect launcher pods as well.
I wonder how people get around this when taints are set on the nodes

Maybe I'm missing something, in which case my apologies.

**Comment by dbkegley** [comment]
Hi @JarritB, thanks for filing this! I think this is being addressed for Connect in [this PR](https://github.com/rstudio/helm/pull/335/files#diff-e093ec567402374e44d1c256de177aa70486f565cb50ef6927b52e804b9d19b3)

**Comment by JarritB** [comment]
Thanks for the response. The issue is indeed covered within the PR.
For now, we will keep using the affinity field then, without taints, and are looking forward to implementing it when ready.
