### ISSUE TITLE
add mountOptions for homeStorage | RSW

### ISSUE THREAD

**Issue by jptrmn** [rstudio/helm#382]
Hi,
is it possible to add the `mountOptions` field to the `homeStorage` PVC spec template?

In the meantime, what would be the cleanest way to apply custom mountOptions for the homeStorage PVC?

Thanks,
Josef

**Comment by colearendt** [comment]
Howdy @jptrmn ! Unfortunately, this has to be set in the PV today 😞 This is something I am not a huge fan of in the kubernetes ecosystem.

We have an example here:
https://github.com/rstudio/helm/blob/ab1d0bfe8aae64e2ff76492f6e581fa798e8c8de/examples/workbench/rstudio-workbench-with-pv.yaml#L32

And upvotes here are always appreciated: https://github.com/kubernetes/kubernetes/issues/96284 (does not solve the PVC issue, but solves the mount-options-set-by-a-non-cluster-admin issue 😄

**Comment by colearendt** [comment]
Closing this since there is unfortunately nothing we can do about setting mount options on PVCs
