### ISSUE TITLE
no option for terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by Almenon** [rstudio/helm#411]
In a call w/ posit they told me that there is a issue where kubernetes might kill a pod before it can finish deactivating the license. To prevent that I should let the pod run for two minutes before killing it. I'm presuming to do that I would set `terminationGracePeriodSeconds`. However, there is no option to pass that into the helm values, and I don't use kustomize. Can that option be added in please?

**Comment by colearendt** [comment]
Howdy @Almenon ! Yes, this sounds like a great option to add, thanks for sending this across!
