### ISSUE TITLE
[PM] Error: Git builder not found

### ISSUE THREAD

**Issue by Almenon** [rstudio/helm#425]
This error is rather frustrating, because I'm running the command to create a git builder, so I don't understand why it would need to find one. 

```
$ rspm create git-builder --url=https://x-token-auth:ds-workspace-access-token@bitbucket.org/ispottv/dsrutils.git --source=prod-internal-src --build-trigger=commits
Cloning repo and waiting for initial package builds...

This could take some time depending on the size of the repo and the number of package builds...

Error: Git builder not found.
```

What's also weird is this appears to work randomly. One time I ran a command, it failed, ran the exact same command again, and it worked.

What's also very weird is when I list the git builders I see builders, but they have weird names. 

```
Git Builders:
- B2Ig1sRG1nne
    Source: prod-internal-src
    URL: https://x-token-auth:censored@bitbucket.org/ispottv/dsrutils.git
    Trigger: commits
    Branch: 
    Credential Name: none
```

Chart version 0.5.13

**Comment by colearendt** [comment]
That is really strange and concerning 😮 Sorry for the trouble here @Almenon !

This honestly may be something to report to the product team - have you submitted a support ticket on this issue yet?

If so, please link here! The helm chart may be involved here, but this definitely seems more like a potential product issue!

Are you using our public docker image? Or your own container?

**Comment by Almenon** [comment]
Public docker image. I submitted a support ticket, the error is extremely weird. More details in the ticket.

#96579

**Comment by calebAtIspot** [comment]
Support recommended that I use a external database rather than a EBS volume. Once I did that the error went away.
