### ISSUE TITLE
Add documentation/examples on how to create/consume secrets for license files

### ISSUE THREAD

**Issue by tnederlof** [rstudio/helm#426]
# Proposal

Add to each product chart README a recommendation to store license files as secrets and provide examples on how to create the secret and what values have to be set.

# Reason

More and more customers are using license files for each of the products, and it is becoming the standard. Passing the license file contents in at `helm install` is clunky, and customers struggle with ensuring the format makes it into the container successfully.

**Comment by tnederlof** [comment]
@colearendt I am happy to take this on and add to the READMEs if you think its a good idea

**Comment by colearendt** [comment]
Sounds great! Related to #427
