### ISSUE TITLE
Change default deployment strategy for each product chart

### ISSUE THREAD

**Issue by tnederlof** [rstudio/helm#439]
Each of the product helm charts has a default value of `strategy.type: "RollingUpdate"` which may not be appropriate since new product versions could have database migrations and don't support the rolling update style of running two product version simultaneously. We should consider changing this default to `Recreate`

**Comment by edavidaja** [comment]
see also: #424

**Comment by NicholasRaymondiSpot** [comment]
Valid suggestion, why was it closed?
