### ISSUE TITLE
Support setting `ImagePullPolicy` for session images

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#59]
Would be great to have.

Currently this is not possible in 

https://github.com/rstudio/helm/blob/dd607de994a5810d662e1a1d7287feeeddc9e0c6/charts/rstudio-workbench/values.yaml#L9-L18

Would be great for rolling tags when using custom images.

**Comment by colearendt** [comment]
I have improved documentation here: https://github.com/rstudio/helm/tree/main/charts/rstudio-workbench#rstudio-profiles

**Comment by pat-s** [comment]
Thanks, I'll try again soon! So far I couldn't get it working but happy to give it another try 👍  Thanks for the new descriptive examples.

**Comment by pat-s** [comment]
Seems to work now 🥳️

(Actually I don't know why, I haven't changed this code part since I last checked but I've deployed multiple versions of the same tag today and each time the newest session image was downloaded).

**Comment by colearendt** [comment]
Good to hear things are working for you! Let us know if you run into this again - we are working on a way to make it a bit easier to set config settings like this for session images, so hopefully that will make life easier in the future!
