### ISSUE TITLE
RSW: issues with `rstudio-workbench-preview` image

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#64]
I've tried deploying with the `rstudio/rstudio-workbench-preview:preview` and `rstudio/rstudio-workbench:latest` images and got

```
  Normal   Scheduled  69s                default-scheduler  Successfully assigned rsw/rsw-5474887d98-bvff7 to ip-10-0-1-37.eu-central-1.compute.internal
  Normal   Pulling    68s                kubelet            Pulling image "rstudio/rstudio-workbench-preview:2021.09.0-351.pro6"
  Normal   Pulled     67s                kubelet            Successfully pulled image "rstudio/rstudio-workbench-preview:2021.09.0-351.pro6" in 1.172111632s
  Normal   Pulled     66s                kubelet            Container image "prom/graphite-exporter:v0.9.0" already present on machine
  Normal   Created    66s                kubelet            Created container exporter
  Normal   Started    66s                kubelet            Started container exporter
  Normal   Created    24s (x4 over 66s)  kubelet            Created container rstudio
  Warning  Failed     24s (x4 over 66s)  kubelet            Error: failed to start container "rstudio": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "tini": executable file not found in $PATH: unknown
```

Seems like `tini` is not installed in these images?

**Comment by colearendt** [comment]
Apologies for the delayed notice here. This has been available as the `dev` version of the chart now for a little bit:
```
helm template --devel rsw rstudio/rstudio-workbench
```

We are taking our time publishing it properly because of some breaking changes and trying to mitigate issues / improve testing coverage. Please let us know if you run into any issues!

**Comment by pat-s** [comment]
Thanks, given that the chart has now been adapted to work with the 2021.09 release, this might just work :)
This was also just a short FYI issue as I came across it, not a big deal.

We use terraform to deploy the chart and usually try not to use `helm` commands directly, but that is nevertheless good to know 👍
