### ISSUE TITLE
RSW: Clarification on `launcherPub`

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#65]
`launcherPub` is not further documented in `values.yml`. 

Even though I assume from the README contents it should not be set/changed as it will be auto-generated from `launcherPem`, it is unclear to me what its default `False` will do in the background. 

I think adding a short comment here could be helpful.

**Comment by colearendt** [comment]
We improved the documentation message here. Hopefully this helps!

> An inline launcher.pub key to pair with launcher.pem. If false (the default), we will try to generate a launcher.pub from the provided launcher.pem
