### ISSUE TITLE
RSW: mounting custom PAM profiles

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#73]
I've mounted a custom PAM profile via `volumes` and `volumeMounts`.

[Due to the fact that direct file mounts are not possible in k8s and that dir mounts overwrite existing contents](https://stackoverflow.com/questions/33415913/whats-the-best-way-to-share-mount-one-file-into-a-pod), I am mounting the profile into an empty dir and then create a softlink into `/etc/pam.d/`.

Would it be possible to include some heuristic in the helm chart to create the file at the correct place via a custom setting in `values.yml` or help with the symlink?

**Comment by colearendt** [comment]
Oh wow, you're good 😄 I'll be merging #75 soon, which should exactly solve your problem! I love happy coincidences! 😄 

Would you mind taking a look before I merge to see if it looks promising? You can also use `helm-git` to access and try it directly if you'd like.

**Comment by colearendt** [comment]
Also, it should be possible to mount specific files... The emptydir problem that the one poster on SO references sounds like either (1) a bug in their volume or (2) a bug in Kubernetes

https://github.com/rstudio/helm/blob/cc0b01013bb3082962b07a16b432158bb2716c26/charts/rstudio-workbench/templates/_helpers.tpl#L119-L121

**Comment by pat-s** [comment]
> I have used this subPath convention elsewhere with success 😄

Interesting! I've tried it and for me it didn't work, i.e. everything else in the dir was removed. (k8s v1.21).

Happy to try out the new PAM integration! Nice coincidence ;)

**Comment by colearendt** [comment]
This should be taken care of by #75
