### ISSUE TITLE
RSW: Consistent use of `RSP` and `RSW` acronyms in env vars

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#78]
FYI, e.g. during license activation I see 

chart `v0.5-rc4`

```
+ trap deactivate EXIT
+ RSP_LICENSE=
+ RSP_LICENSE_SERVER=$REDACTED
+ RSW_LICENSE_FILE_PATH=/etc/rstudio-server/license.lic


+ unset RSP_LICENSE
+ unset RSP_LICENSE_SERVER
+ unset RSW_LICENSE
+ unset RSW_LICENSE_SERVER
```

**Comment by colearendt** [comment]
Thanks for the report! - we definitely may have missed something here. Trying to support backwards compatibility while moving from RSP to RSW all the things!
